---
- hosts: all

  tasks:
    - include_role:
        name: 2do_parcial
    
    - name: "Otra tarea"
      debug:
        msg: "Despues de la ejecucion del rol"

    - name: "ROL: crear_estructura_directorios"
      import_role:
        name: crear_estructura_directorios

    - name: "ROL: generar_archivos"
      import_role:
        name: generar_archivos

    - name: "ROL: configurar_sudoers"
      import_role:
        name: configurar_sudoers
